version: '3'
services:
  cf_exp:
    container_name: container1
    image: python_env:latest
    volumes:
      - .:/workspace
      - packages:/root/.local/share
      - /mnt/nas5/lab_member_directories/2024_sumiya:/mydata
    ports:
      - "8070:8070"
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
volumes:
  packages: